spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  rabbitmq:
    host: eagle.rmq.cloudamqp.com
    username: iclcnsiv
    password: PuivyPKXprkDmUEMh0sPH3lepJZBRWZi
    virtual-host: iclcnsiv
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8701/eureka,http://localhost:8702/eureka,http://localhost:8761/eureka

management:
  security:
    enabled: false